name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Package plugin
        run: mkdir release && zip -j -r release/bob-plugin-latex-ocr-${{ steps.tag.outputs.tag }}.bobplugin ./src/*

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/bob-plugin-latex-ocr-${{ steps.tag.outputs.tag }}.bobplugin
          asset_name: bob-plugin-latex-ocr-${{ steps.tag.outputs.tag }}.bobplugin
          tag: ${{ github.ref }}
          overwrite: true
          body: "Release Bob plugin!"
